"use client";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import Theme from "../components/Theme";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={Theme}>
      <html lang="en" className={"main"}>
        <body>{children}</body>
      </html>
    </ThemeProvider>
  );
}
